@ECHO OFF
CLS
ECHO зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©
ECHO Ё FivePro 2.0 - February 94                                                   Ё
ECHO Ё (c) A.Linares y F.Pulp╒n, 1993-4                                            Ё
ECHO юддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды
ECHO Ъ

clipper %1 /n/w/i..\include

blinker fi %1 lib ..\lib\FivePro2, ..\lib\objects3

%1
