//----------------------------------------------------------------------------//
//  FivePro 2.0 - Tutorial
//  (c) A.Linares, F.Pulp¢n 1993-4
//
//  Contruir con BUILD Tutor02
//  Build with   BUILD Tutor02
//----------------------------------------------------------------------------//

#include "FivePro.ch"

//----------------------------------------------------------------------------//

function Main()

   local oWnd

   DEFINE WINDOW oWnd FROM 3, 6 TO 20, 70 TITLE "FiveWin 1.4"
      
   ACTIVATE WINDOW oWnd

return

//----------------------------------------------------------------------------//
