#ifndef _COLORS_H
#define _COLORS_H

#define WHITE_ON_BLACK     7
#define BR_WHITE_ON_BLACK 15

#define GREEN_ON_BLUE     18
#define WHITE_ON_BLUE     23
#define BR_GREEN_ON_BLUE  26
#define BR_CYAN_ON_BLUE   27
#define BR_RED_ON_BLUE    28
#define YELLOW_ON_BLUE    30
#define BR_WHITE_ON_BLUE  31

#define BR_WHITE_ON_GREEN 47

#define BLACK_ON_CYAN     48
#define BLUE_ON_CYAN      49
#define GREEN_ON_CYAN     50
#define CYAN_ON_CYAN      51
#define RED_ON_CYAN       52
#define MAGENTA_ON_CYAN   53
#define BROWN_ON_CYAN     54
#define WHITE_ON_CYAN     55
#define GREY_ON_CYAN      56
#define BR_BLUE_ON_CYAN   57
#define BR_RED_ON_CYAN    60
#define YELLOW_ON_CYAN    62
#define BR_WHITE_ON_CYAN  63

#define BLACK_ON_WHITE   112

#endif
