#ifndef _EGACOLOR_CH
#define _EGACOLOR_CH

#define REG_CYAN       3
#define REG_MAGENTA    5
#define REG_BROWN      6
#define REG_BR_BLUE    9
#define REG_BR_RED    12
#define REG_YELLOW    14

#define CLR_OLIVE      6
#define CLR_BROWN     20
#define CLR_MINT      30
#define CLR_PURPLE    37
#define CLR_SALMON    39
#define CLR_OCEAN     43
#define CLR_LILA      45
#define CLR_ORANGE    46
#define CLR_BR_YELLOW 54
#define CLR_YELLOW    55

#endif
